language: node_js

node_js:
- "12"

before_install:
- npm ci
- npx version-from-git --travis

install:
- npm run prepublishOnly

before_deploy:
- git config --local user.name "William Wong"
- git config --local user.email "compulim@hotmail.com"
- git tag dev

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - directLine.js
  # file_glob: true
  on:
    branch: streamingextension
  overwrite: true
  prerelease: true
  skip_cleanup: true
