language: node_js

node_js:
- "12"

before_install:
- npm ci
- npx version-from-git --travis

install:
- npm run prepublishOnly

before_deploy:
- npm pack
- git config --local user.name "William Wong"
- git config --local user.email "compulim@hotmail.com"
- export TRAVIS_TAG=dev
- git tag $TRAVIS_TAG

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  body: "This build will be updated on every push. Please do not use it for production use."
  file:
  - directLine.js
  - botframework-directlinejs-*.tgz
  file_glob: true
  name: "Continuous integration build"
  on:
    branch: streamingextensions
  overwrite: true
  prerelease: true
  skip_cleanup: true
