sudo: required

language: node_js

node_js:
  - "10"

install:
  - sudo apt-get install jq
  - git checkout -b temp-ci
  - npx version-from-git --travis --no-git-tag-version
  - npm install
  - lerna version --force-publish --no-git-tag-version --no-push --yes `cat package.json | jq -r .version`
  - npm run bootstrap

before_script:
  - npm run build

before_deploy:
  - npm run prepublishOnly
  - git config --local user.name "Bot Framework"
  - git config --local user.email "botframework@microsoft.com"
